package hr.fer.oprpp1.hw02.prob1;

/**
 * Used to represent a token generated by a Lexer
 */
public class Token {
    /**
     * type - token type
     */
    private final TokenType type;
    /**
     * value - stored value of the token
     */
    private final Object value;

    /**
     * Constructor used to generate a token
     * @param type token type
     * @param value to be stored in this token
     */
    public Token(TokenType type, Object value) {
        this.type = type;
        this.value = value;
    }

    /**
     * Getter method for token type
     * @return the type of this token
     */
    public TokenType getType() {
        return type;
    }

    /**
     * Getter method for the value stored in this token
     * @return stored value of this token
     */
    public Object getValue() {
        return value;
    }

}
